### ISSUE TITLE
wget --version

### ISSUE THREAD

**Issue by dimakad** [therealOri/PolyLock#3]
wget version cannot be checked with --version on windows. 
same for curl....

PS C:\github\AutoTunerCommander\project_files\PolyLock> wget --version
wget : The remote name could not be resolved: '--version'
At line:1 char:1
+ wget --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by therealOri** [comment]
I am not sure as to why the command prompt doesn't like wget but as of right now polylock is using the python version of wget and no longer needs to check for it.
